services:
  postgres:
    container_name: memories_bd
    image: postgis/postgis:16-master
    env_file:
      - .env
    expose:
      - ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: redis
    image: redis:7-alpine
    expose:
      - 6379
    ports:
      - 6379:6379
    restart: always

  api:
    container_name: memories_api
    build:
      context: ./
    env_file:
      - .env
    environment:
      - IS_DOCKER=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./:/app
      - /app/node_modules
    expose:
      - ${PORT}:4040
    ports:
      - ${PORT}:4040
    command: sh -c "npm run db:setup && npm run start"
    depends_on:
      - postgres
      - redis
    restart: always

volumes:
  pgdata:
