version: '3.8'

services:
  api:
    container_name: memories_api
    build:
      context: ./
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    expose:
      - ${PORT}
    ports:
      - ${PORT}:4040
    command: sh -c "npm run db:setup && npm run start"
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: memories_bd
    image: postgis/postgis:16-master
    env_file:
      - .env
    expose:
      - ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always

  nuxt:
    container_name: memories_app
    build:
      context: ./front
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - ${NUXT_PORT}:3000
    command: npm run build && npm run start
    depends_on:
      - api
    restart: always

volumes:
  pgdata:
