export default {
    data() {
        return {
            spacesData: [
                {
                    id: 1,
                    coworking_name: "Artinov Group",
                    first_price: 50,
                    last_price: 3000,
                    address: "м. Вінниця, вул. Миколи Оводова, 22",
                    coworking_photo: "../../main-photo-1.jpg",
                    advantages: [
                        {name: "Генератор", icon: "../../generator.svg", selected: false},
                        {name: "Чай / кава", icon: "../../coffee.svg", selected: true},
                        {name: "Укриття", icon: "../../shelter.svg", selected: false},
                        {name: "Старлінк", icon: "../../starlink.svg", selected: false},
                        {name: "Кімната відпочинку", icon: "../../restroom.svg", selected: false},
                        {name: "Парковка", icon: "../../parking.svg", selected: false},
                        {name: "Дошка", icon: "../../board.svg", selected: true},
                        {name: "Проектор", icon: "../../projector.svg", selected: true},
                        {name: "Кухня", icon: "../../kitchen.svg", selected: true},
                        {name: "Швидкісний інтернет", icon: "../../internet.svg", selected: true},
                    ],
                    description:
                        "Зручне розташування нашого простору дозволяє максимально швидко добиратись як до нас, так і до найважливіших локацій міста. Ми знаходимось у самому серці міста — біля Водонапірної вежі на Європейській площі. У нашому просторі ви маєте великий вибір локацій, які ви можете зарезервувати для себе - проведення днів народжень, корпоративів та інших персональних заходів. У нас є дві окремі та зручні коворкінг-зони. Перша знаходиться на другому поверсі Артинова, друга на першому (колишня локація кінозалу). Тут кожен коворкер отримує своє персональне робоче місце, шафу для зберігання особистих речей та, окремі від загального простору, кухню, штурмову, дві скайп-кімнати, гардеробну, вбиральню та душову.",
                    seatingArrangements: [
                        {icon: "../eight_seats_in_a_circle.svg", selected: true},
                        {icon: "../places_rectangle.svg", selected: true},
                        {icon: "../places_two_circles.svg", selected: true},
                        {icon: "../two_rows_of_seats.svg", selected: true},
                    ],
                    social: [
                        {
                            name: "facebook",
                            link: "https://www.facebook.com/artinov.space",
                            icon: "facebook.png",
                        },
                        {
                            name: "instagram",
                            link: "https://www.instagram.com/artinov.space/",
                            icon: "instagram.png",
                        },
                    ],
                    spaces: [
                        {
                            space_name: "OpenSpace",
                            space_photo: "../../cow-1-space-1.jpg",
                            amount: 180,
                        },
                        {
                            space_name: "Переговорна",
                            space_photo: "../../cow-1-space-2.jpg",
                            amount: 10,
                        },
                        {
                            space_name: "Коворкінг-зона 1",
                            space_photo: "../../cow-1-space-3.jpg",
                            amount: 50,
                        },
                        {
                            space_name: "Коворкінг-зона 2",
                            space_photo: "../../cow-1-space-4.jpg",
                            amount: 50,
                        },
                        {
                            space_name: "Дві скайп-кімнати",
                            space_photo: "../../cow-1-space-5.jpg",
                            amount: 4,
                        },
                    ],
                    email: "artinov.space@gmail.com",
                    phone: "+38 093 226-22-32",
                    start_work: "9:00",
                    end_work: "21:00",
                    workday_start: "9:00",
                    workday_end: "21:00",
                    dayoff_start: "9:00",
                    dayoff_end: "21:00",
                },
                {
                    id: 2,
                    coworking_name: "iHUB",
                    first_price: 400,
                    last_price: 2500,
                    workday: 800,
                    weekend: 250,
                    amount: 65,
                    address: "м. Вінниця, вул. Пушкіна, 11",
                    coworking_photo: "../../main-photo-2.jpg",
                    advantages: [
                        {name: "Генератор", icon: "../../generator.svg", selected: false},
                        {name: "Чай / кава", icon: "../../coffee.svg", selected: true},
                        {name: "Укриття", icon: "../../shelter.svg", selected: false},
                        {name: "Старлінк", icon: "../../starlink.svg", selected: true},
                        {name: "Кімната відпочинку", icon: "../../restroom.svg", selected: true},
                        {name: "Парковка", icon: "../../parking.svg", selected: true},
                        {name: "Дошка", icon: "../../board.svg", selected: false},
                        {name: "Проектор", icon: "../../projector.svg", selected: false},
                        {name: "Кухня", icon: "../../kitchen.svg", selected: true},
                        {name: "Швидкісний інтернет", icon: "../../internet.svg", selected: true},
                    ],
                    description:
                        "iHUB – це місце, де інновації відбуваються щодня. Молоді да досвідчені підприємці працюють, спілкуються та творять у приміщеннях сучасного коворкінгу, поєднаного з історичною архітектурою у самому центрі міста. Просторий open space, приватні офіси, оснащенні технікою дизайнерські переговорні кімнати, зони для відпочинку та зали для івентів – ми надаємо все, що необхідно для розвитку вашого стартапу. У нас тільки актуальні тематики заходів та топові спікери. Нудьгувати не прийдеться, адже Ви зможете знайти івенти на будь-який смак: майстер-класи, воркшопи, хакатони, зустрічі з інвесторами, пітчинги та ще багато іншого. iHUB не просто ком’юніті – це сім’я, де Ви можете приєднатись до найталановитіших підприємців та стартапів, знайти собі партнерів чи клієнтів, співробітників та інвесторів. Обирайте один з наших сервісів та програм, що допоможуть злетіти Вашому проєкту.",
                    seatingArrangements: [
                        {icon: "../eight_seats_in_a_circle.svg", selected: true},
                        {icon: "../places_p.svg", selected: true},
                        {icon: "../places_rectangle.svg", selected: true},
                        {icon: "../two_rows_of_seats.svg", selected: true},
                    ],
                    social: [
                        {
                            name: "instagram",
                            link: "https://www.instagram.com/ihubvinnytsia/",
                            icon: "instagram.png",
                        },
                    ],
                    spaces: [
                        {
                            space_name: "Conference Space",
                            space_photo: "../../cow-2-space-1.jpg",
                            amount: 30,
                        },
                        {
                            space_name: "Робочі місця та персональні офіси",
                            space_photo: "../../cow-2-space-2.jpg",
                            amount: 20,
                        },
                        {
                            space_name: "Переговорні кімнати",
                            space_photo: "../../cow-2-space-3.jpg",
                            amount: 8,
                        },
                        {
                            space_name: "Конференц зал",
                            space_photo: "../../cow-2-space-4.jpg",
                            amount: 20,
                        },
                        {
                            space_name: "FLEX-офіси для команд",
                            space_photo: "../../cow-2-space-5.jpg",
                            amount: 10,
                        },
                    ],
                    email: "post@ihub.world",
                    phone: "+38 050 426-16-16 ",
                    start_work: "9:00",
                    end_work: "21:00",
                    workday_start: "9:00",
                    workday_end: "21:00",
                    dayoff_start: "9:00",
                    dayoff_end: "21:00",
                },
                {
                    id: 3,
                    coworking_name: "Miro Space",
                    first_price: 200,
                    last_price: 2500,
                    workday: 200,
                    weekend: 2500,
                    amount: 97,
                    address: "м. Вінниця, вул. Келецька, 57",
                    coworking_photo: "../main-photo-3.jpg",
                    advantages: [
                        {name: "Генератор", icon: "../../generator.svg", selected: false},
                        {name: "Чай / кава", icon: "../../coffee.svg", selected: true},
                        {name: "Укриття", icon: "../../shelter.svg", selected: false},
                        {name: "Старлінк", icon: "../../starlink.svg", selected: false},
                        {name: "Кімната відпочинку", icon: "../../restroom.svg", selected: false},
                        {name: "Парковка", icon: "../../parking.svg", selected: false},
                        {name: "Дошка", icon: "../../board.svg", selected: true},
                        {name: "Проектор", icon: "../../projector.svg", selected: false},
                        {name: "Кухня", icon: "../../kitchen.svg", selected: false},
                        {name: "Швидкісний інтернет", icon: "../../internet.svg", selected: true},
                    ],
                    description:
                        "Miro Space  Epicenter of innovations. Наша ціль  – створити iнновацiйне середовище i творчу атмосферу для роботи з метою розвитку нових технологiй в сферi блокчейну та IT.  Miro Space  – робочий простiр iнновацiй, в якому поєднали дiловий досвiд створення офiсiв з творчим пiдходом. Це мiсце для втiлення проєктiв, дiлового спiлкування, корисних подiй i знайомств, середовище для розвитку i примноження.",
                    seatingArrangements: [
                        {icon: "../eight_seats_in_a_circle.svg", selected: true},
                        {icon: "../places _two_by_twelve.svg", selected: true},
                        {icon: "../places_p.svg", selected: true},
                        {icon: "../places_two_circles.svg", selected: true},
                    ],
                    social: [
                        {
                            name: "facebook",
                            link: "https://www.facebook.com/mirospace.ua/",
                            icon: "facebook.png",
                        },
                        {
                            name: "telegram",
                            link: "https://t.me/Miro_Space",
                            icon: "telegram.png",
                        },
                        {
                            name: "instagram",
                            link: "https://www.instagram.com/mirospace.ua/",
                            icon: "instagram.png",
                        },
                    ],
                    spaces: [
                        {
                            space_name: "Хромакей Студія",
                            space_photo: "../../cow-3-space-1.jpg",
                            amount: 10,
                        },
                        {
                            space_name: "Скайп-руми",
                            space_photo: "../../cow-3-space-2.jpg",
                            amount: 10,
                        },
                        {
                            space_name: "Переговорні кімнати",
                            space_photo: "../../cow-3-space-3.jpg",
                            amount: 10,
                        },
                        {
                            space_name: "Конференц зал",
                            space_photo: "../../cow-3-space-4.jpg",
                            amount: 10,
                        },
                        {
                            space_name: "Навчальний клас",
                            space_photo: "../../cow-3-space-5.jpg",
                            amount: 24,
                        },
                        {
                            space_name: "Малий конференц-зал",
                            space_photo: "../../cow-3-space-6.jpg",
                            amount: 24,
                        },
                        {
                            space_name: "Робочi мiсця",
                            space_photo: "../../cow-3-space-7.jpg",
                            amount: 21,
                        },
                        {
                            space_name: "Великий конференц-зал",
                            space_photo: "../../cow-3-space-8.jpg",
                            amount: 124,
                        },
                    ],
                    email: "mirospace.ua@gmail.com",
                    phone: "+38 093 503-01-01",
                    start_work: "9:00",
                    end_work: "21:00",
                    workday_start: "9:00",
                    workday_end: "21:00",
                    dayoff_start: "9:00",
                    dayoff_end: "21:00",
                },
                {
                    id: 4,
                    coworking_name: "CHERDAK SPASE",
                    first_price: 75,
                    last_price: 5000,
                    workday: 300,
                    weekend: 250,
                    amount: 75,
                    address: "м. Вінниця, вул. Соборна, 24",
                    coworking_photo: "../../main-photo-4.jpg",
                    advantages: [
                        {name: "Генератор", icon: "../../generator.svg", selected: true},
                        {name: "Чай / кава", icon: "../../coffee.svg", selected: true},
                        {name: "Укриття", icon: "../../shelter.svg", selected: true},
                        {name: "Старлінк", icon: "../../starlink.svg", selected: true},
                        {name: "Кімната відпочинку", icon: "../../restroom.svg", selected: false},
                        {name: "Парковка", icon: "../../parking.svg", selected: true},
                        {name: "Дошка", icon: "../../board.svg", selected: false},
                        {name: "Проектор", icon: "../../projector.svg", selected: false},
                        {name: "Кухня", icon: "../../kitchen.svg", selected: false},
                        {name: "Швидкісний інтернет", icon: "../../internet.svg", selected: true},
                    ],
                    description:
                        "Простори для роботи та івентів. Ми забезпечуємо ваш робочий простір усім необхідним.",
                    seatingArrangements: [
                        {icon: "../eight_seats_in_a_circle.svg", selected: true},
                        {icon: "../places_rectangle.svg", selected: true},
                        {icon: "../places_two_circles.svg", selected: true},
                        {icon: "../two_rows_of_seats.svg", selected: true},
                    ],
                    social: [
                        {
                            name: "instagram",
                            link: "https://instagram.com/cherdak.space?igshid=MTk0NTkyODZkYg==",
                            icon: "instagram.png",
                        },
                    ],
                    spaces: [
                        {
                            space_space_name: "SPACE",
                            space_photo: "../../cow-4-space-1.jpg",
                            amount: 80,
                        },
                        {
                            space_space_name: "OPEN SPACE",
                            space_photo: "../../cow-4-space-2.jpg",
                            amount: 100,
                        },
                        {
                            space_space_name: "MEETING ROOM",
                            space_photo: "../../cow-4-space-3.jpg",
                            amount: 20,
                        },
                        {
                            space_space_name: "LOUNGE ZONE",
                            space_photo: "../../cow-4-space-4.jpg",
                            amount: 20,
                        },
                        {
                            space_space_name: "FLEX-офіси для команд",
                            space_photo: "../../cow-4-space-5.jpg",
                            amount: 24,
                        },
                        {
                            space_space_name: "CALL ROOM",
                            space_photo: "../../cow-4-space-6.jpg",
                            amount: 2,
                        },
                        {
                            space_space_name: "BUSINESS ROOM",
                            space_photo: "../../cow-4-space-7.jpg",
                            amount: 24,
                        },
                    ],
                    email: "info@cherdak-space.com",
                    phone: "+38 097 902-88-88",
                    start_work: "9:00",
                    end_work: "21:00",
                    work_day_start: "9:00",
                    work_day_end: "21:00",
                    dayoff_start: "9:00",
                    dayoff_end: "21:00",
                },
                {
                    id: 5,
                    coworking_name: "Ume place",
                    first_price: 260,
                    last_price: 5000,
                    workday: 260,
                    weekend: 5000,
                    amount: 75,
                    address: "м. Вінниця, просп. Космонавтів, 30 А",
                    coworking_photo: "../../main-photo-5.jpg",
                    advantages: [
                        {name: "Генератор", icon: "../../generator.svg", selected: true},
                        {name: "Чай / кава", icon: "../../coffee.svg", selected: true},
                        {name: "Укриття", icon: "../../shelter.svg", selected: true},
                        {name: "Старлінк", icon: "../../starlink.svg", selected: true},
                        {name: "Кімната відпочинку", icon: "../../restroom.svg", selected: false},
                        {name: "Парковка", icon: "../../parking.svg", selected: false},
                        {name: "Дошка", icon: "../../board.svg", selected: false},
                        {name: "Проектор", icon: "../../projector.svg", selected: false},
                        {name: "Кухня", icon: "../../kitchen.svg", selected: true},
                        {name: "Швидкісний інтернет", icon: "../../internet.svg", selected: true},
                    ],
                    description:
                        "Ume.Place — це про приватність, комфорт та безпеку. Ми коворкінг закритого типу з великою кількістю простору та можливостей. Івент-менеджер допоможе організувати події, оператор та монтажер — створити контент, а наші адміністратори попіклуються про твій комфорт.",
                    seatingArrangements: [
                        {icon: "../eight_seats_in_a_circle.svg", selected: true},
                        {icon: "../places_rectangle.svg", selected: true},
                        {icon: "../two_rows_of_seats.svg", selected: true},
                    ],
                    social: [
                        {
                            name: "facebook",
                            link: "https://www.facebook.com/ume.place.ua",
                            icon: "facebook.png",
                        },
                        {
                            name: "instagram",
                            link: "https://www.instagram.com/ume.place/",
                            icon: "instagram.png",
                        },
                    ],
                    email: "info@ume.place",
                    phone: "+38 068 787-49-23",
                    start_work: "6:00",
                    end_work: "22:00",
                    workday_start: "6:00",
                    workday_end: "22:00",
                    dayoff_start: "6:00",
                    dayoff_end: "22:00",
                },
                {
                    id: 6,
                    coworking_name: "EduHUB",
                    first_price: 50,
                    last_price: 3000,
                    address: "м. Вінниця, Героїв поліції, 28",
                    amount: 60,
                    coworking_photo: "../../main-photo-6.jpg",
                    advantages: [
                        {name: "Генератор", icon: "../../generator.svg", selected: false},
                        {name: "Чай / кава", icon: "../../coffee.svg", selected: true},
                        {name: "Укриття", icon: "../../shelter.svg", selected: false},
                        {name: "Старлінк", icon: "../../starlink.svg", selected: false},
                        {name: "Кімната відпочинку", icon: "../../restroom.svg", selected: false},
                        {name: "Парковка", icon: "../../parking.svg", selected: false},
                        {name: "Дошка", icon: "../../board.svg", selected: true},
                        {name: "Проектор", icon: "../../projector.svg", selected: true},
                        {name: "Кухня", icon: "../../kitchen.svg", selected: true},
                        {name: "Швидкісний інтернет", icon: "../../internet.svg", selected: true},
                    ],
                    description:
                        "EduHUB - це освітній креативний простір в центрі міста, щоб працювати, навчатись і надихатися, генерувати та втілювати нові і прогресивні ідеї, ділитися власними досягненнями та знаходити креативних друзів-однодумців. Організувати тематичні івенти, творчі й продуктивні посиденьки, семінари, майстер-класи, навчальні заняття, лекції, працювати над стартапами, креативити й надихатися за філіжанкою запашної кави.",
                    seatingArrangements: [
                        {icon: "../eight_seats_in_a_circle.svg", selected: true},
                        {icon: "../places_rectangle.svg", selected: true},
                        {icon: "../places_two_circles.svg", selected: true},
                        {icon: "../two_rows_of_seats.svg", selected: true},
                    ],
                    social: [
                        {
                            name: "facebook",
                            link: "https://www.facebook.com/EduHubVinnytsia",
                            icon: "facebook.png",
                        },
                        {
                            name: "telegram",
                            link: "https://t.me/IT_Academy_Vinnytsia",
                            icon: "telegram.png",
                        },
                        {
                            name: "viber",
                            link: "viber://chat?number=+380674317424",
                            icon: "viber.png",
                        },
                        {
                            name: "instagram",
                            link: "https://www.instagram.com/ita.in.ua/",
                            icon: "instagram.png",
                        },
                    ],
                    spaces: [
                        {
                            space_name: "Sea room",
                            space_photo: "../../cow-6-space-1.jpg",
                            amount: 20,
                        },
                        {
                            space_name: "Magenta",
                            space_photo: "../../cow-6-space-2.jpg",
                            amount: 10,
                        },
                        {
                            space_name: "Hack room",
                            space_photo: "../../cow-6-space-3.jpg",
                            amount: 20,
                        },
                        {
                            space_name: "Square",
                            space_photo: "../../cow-6-space-4.jpg",
                            amount: 10,
                        },
                    ],
                    email: "",
                    phone: "+38 067 431-74-24",
                    start_work: "9:00",
                    end_work: "21:00",
                    workday_start: "9:00",
                    workday_end: "21:00",
                    dayoff_start: "9:00",
                    dayoff_end: "21:00",
                },
            ],
        };
    },
};
